home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObjectView.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObjectView.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category'),
    path('bucket/',include(bucket_urls)),
    path('<slug:slug>/',views.ProductDetailView.as_view(),name='detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='order_create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    sub_category = models.ForeignKey('self',on_delete=models.CASCADE,related_name='scategory',blank=True,null=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home:category',args=[self.slug])

class Product(models.Model):
    category = models.ManyToManyField(Category,related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,unique=True)
    image = models.ImageField()
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('home:detail', args=[self.slug])

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render , get_object_or_404 ,redirect
from django.views import View
from . import models
from . import tasks
from django.contrib import messages
from utils import IsAdminUserMixin
from orders import forms
# Create your views here.


class HomeView(View):
    def get(self,request,category_slug=None):
        products = models.Product.objects.filter(available=True)
        categories = models.Category.objects.filter(is_sub=False)
        if category_slug:
            category= models.Category.objects.get(slug=category_slug)
            products = products.filter(category=category)
        return render(request,'home/home.html',{'products':products,'category':categories})


class ProductDetailView(View):
    def get(self,request,slug):
        product = get_object_or_404(models.Product,slug=slug)
        form = forms.CartForms()
        return render(request,'home/detail.html',{'product':product,'form':form})


class BucketHomeView(IsAdminUserMixin,View):
    template_name = 'home/bucket.html'

    def get(self,request):
        objects = tasks.all_bucket_objects_task()
        return render(request,self.template_name,{'objects': objects})


class DeleteBucketObjectView(IsAdminUserMixin,View):
    def get(self,request,key):
        tasks.delete_object_task.delay(key)
        messages.success(request,"your object will be delete soon...","info")
        return redirect('home:bucket')


class DownloadBucketObjectView(IsAdminUserMixin,View):
    def get(self,request,key):
        tasks.download_object_task.delay(key)
        messages.success(request,"your download will start soon...","info")
        return redirect('home:bucket')

home/templates/home/bucket.html
{% extends 'base.html' %}
{% block title %}Bucket{% endblock %}
{% block content %}


    <table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Size</th>
      <th scope="col">Download</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for obj in objects %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ obj.Key }}</td>
      <td>{{ obj.Size|filesizeformat }}</td>
      <td><a href="{% url 'home:download_obj_bucket' obj.Key %}" >download</a></td>
      <td><a href="{% url 'home:delete_obj_bucket' obj.Key %}">delete</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% block title %}Detail {{ product.slug }}{% endblock %}
{% block content %}

  <img src="{{ product.image.url }}"  alt="...">
  <div class="card-body">
    <h3 class="card-title">{{ product.name }}</h3>
    <p class="card-text">{{ product.description }}</p>
    <p class="card-text">{{ product.price }} Tooman</p>
  <small>{{ product.created|date:"Y-m-d" }}</small>
    <br>
    <br>
  <form style="display: ruby" action="{% url 'orders:cart_add' product.id %}" method="POST">
      {% csrf_token %}
      {{ form }}
      <button class="btn btn-secondary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5M3.102 4l1.313 7h8.17l1.313-7zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4m7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2m7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2"/>
</svg></button>
  </form>
  </div>


{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
    {% for cat in category %}

    <div class="btn-group">
      <a href="{{ cat.get_absolute_url }}" class="btn btn-danger">{{ cat.name }}</a>
      <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu">
          {% for sub in cat.scategory.all %}
        <li><a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a></li>
            {% endfor %}
      </ul>
    </div>

{% endfor %}
    <br>
    <br>
    {% for product in products %}
    <div class="card" style="width: 18rem; display: inline-block">
      <img src="{{ product.image.url }}" class="card-img-top" style="height: 12rem;"  alt="...">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
        <p class="card-text">{{ product.description }}</p>
        <p class="card-text">{{ product.price }} Tooman</p>
        <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Detail</a>
      </div>
    </div>

{% endfor %}
{% endblock %}