home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObjectView.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObjectView.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category'),
    path('bucket/',include(bucket_urls)),
    path('<slug:slug>/',views.ProductDetailView.as_view(),name='detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='order_create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from accounts.models import User
from home.models import Product
# Create your models here.


class Order(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='u_orders')
    paid = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['paid', '-updated']

    def get_total_price(self):
        return sum(item.get_cost() for item in self.order_item.all())

    def __str__(self):
        return str(self.user)



class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE,related_name='order_item')
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)

    def get_cost(self):
        return self.price * self.quantity

    def __str__(self):
        return str(self.product)

orders/forms.py
from django import forms


class CartForms(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)

orders/views.py
from django.shortcuts import render ,get_object_or_404 , redirect
from django.views import View
from .cart import Cart
from . import forms
from home.models import Product
from . import models
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart':cart})


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = forms.CartForms(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect('orders:cart')


class OrderDetailView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        order = get_object_or_404(models.Order,id=order_id)
        return render(request,'orders/order.html',{'order':order})

class OrderCreateView(LoginRequiredMixin,View):
    def get(self,request):
        cart = Cart(request)
        order = models.Order.objects.create(user=request.user)
        for item in cart:
            models.OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
        return redirect('orders:order_detail', order.id)

orders/templates/orders/cart.html
{% extends 'base.html' %}
{% block title %}orders{% endblock %}
{% block content %}

<blockquote class="blockquote text-center">

  <footer class="blockquote-footer">{{ user.email }}</footer>
</blockquote>

<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Total Price</th>
      <th scope="col">Remove</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ item.product }}</td>
      <td>{{ item.quantity }}</td>
      <td>{{ item.price }}</td>
      <td>{{ item.total_price }}</td>
      <td><a href="{% url 'orders:cart_remove' item.product.id %}">remove</a></td>
    </tr>
  {% endfor %}
    <tr>
        <th>Total</th>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<a class="btn btn-primary" href="{% url 'orders:order_create' %}">checkout</a>


{% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}
{% block title %}detail-cart{% endblock %}
{% block content %}


<h3 class="text-center">Total Price</h3>
    <p class="text-center">{{ order.get_total_price }} Tooman</p>





{% endblock %}