accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('verify/',views.UserRegisterVerifyCodeView.as_view(),name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),

]

home/urls.py
from django.urls import path, include
from . import views


app_name = 'home'

bucket_urls = [
    path('', views.BucketHomeView.as_view(), name='bucket'),
    path('delete_obj/<str:key>/', views.DeleteBucketObjectView.as_view(), name='delete_obj_bucket'),
    path('download_obj/<str:key>/', views.DownloadBucketObjectView.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('category/<slug:category_slug>/',views.HomeView.as_view(),name='category'),
    path('bucket/',include(bucket_urls)),
    path('<slug:slug>/',views.ProductDetailView.as_view(),name='detail'),
]

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('create/',views.OrderCreateView.as_view(),name='order_create'),
    path('detail/<int:order_id>/',views.OrderDetailView.as_view(),name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('orders/',include('orders.urls',namespace='orders')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  <style>
      .badge:after{
content:attr(value);
font-size:12px;
background: red;
border-radius:50%;
padding:3px;
position:relative;
left:-8px;
top:-10px;
opacity:0.9;
}

  </style>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    />

    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base_styles.css' %}">
    {% block extra_headers %} {% endblock %}
  </head>
  <body>
    <header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home:home' %}" class="nav-link px-2 text-secondary">Home</a></li>

        {% if request.user.is_admin %}
          <li><a href="{% url 'home:bucket' %}" class="nav-link px-2 text-white">bucket</a></li>
        {% endif %}
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'accounts:user_logout' %}" class="nav-link px-2 text-white">logout</a></li>
        {% else %}
            <li><a href="{% url 'accounts:user_login' %}" class="nav-link px-2 text-white">login</a></li>
          <li><a href="{% url 'accounts:register' %}" class="nav-link px-2 text-white">signup</a></li>

        {% endif %}
        <li><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<a href="{% url 'orders:cart' %}"><i class="fa badge" style="font-size:24px" value={{ cart|length }}>&#xf07a;</i></a></li>

        </ul>




      </div>
    </div>
  </header>
    <br />

    <br />
    <div class="jumbotron">
      {% include "inc/messages.html" %} {% block content %} {% endblock content %}
    </div>
    <br />

    <div class="container">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item">
            <a href="" class="nav-link px-2 text-body-secondary">Home</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">Features</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">Pricing</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">FAQs</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link px-2 text-body-secondary">About</a>
          </li>
        </ul>
        <p class="text-center text-body-secondary">© 2023 Company, Inc</p>
      </footer>
    </div>
  </body>
</html>